language: bash

sudo: required

services:
  - docker

install:
  - docker-compose -f ./docker-compose-travis.yml -p tests up -d 

before_script:
  - docker exec -i tests_erlang_1 sh -c "sed -i '/auth.mongo.server/c auth.mongo.server = mongo_server:27017' /emqx_auth_mongo/etc/emqx_auth_mongo.conf"

script:
  - docker exec -i tests_erlang_1 sh -c "make -C /emqx_auth_mongo compile"
  - docker exec -i tests_erlang_1 sh -c "make -C /emqx_auth_mongo eunit"
  - docker exec -i tests_erlang_1 sh -c "make -C /emqx_auth_mongo ct"

after_script:
  - docker-compose -f ./docker-compose-travis.yml -p tests down 
